### ISSUE TITLE
Uncompilable code generated

### ISSUE THREAD

**Issue by robertmircea** [Cysharp/MasterMemory#81]
The following code is not compilable when using the following code to initialize and query MasterMemory under .NET 7:

```csharp

using MasterMemory;
using MasterMemoryDemo;
using MessagePack;

var builder = new DatabaseBuilder();
byte[] data = builder.Build();

// -----------------------

var db = new MemoryDatabase(data);


[MemoryTable("PortedMsisdns"), MessagePackObject(true)]
public class MsisdnInfo
{
    [PrimaryKey]
    public string Msisdn { get; set; }
    public string Operator { get; set; }
}
```

The error message from the compiler is
```
  MemoryDatabase.cs(32, 33): [CS0115] 'MemoryDatabase.Init(Dictionary<string, (int offset, int count)>, ReadOnlyMemory<byte>, MessagePackSerializerOptions)': no suitable method found to override
  MemoryDatabase.cs(16, 24): [CS0534] 'MemoryDatabase' does not implement inherited abstract member 'MemoryDatabaseBase.Init(Dictionary<string, (int offset, int count)>, ReadOnlyMemory<byte>, MessagePackSerializerOptions, int)'
```

**Comment by daleholborow** [comment]
Can confirm - the method Init is generated but is missing the degrees of parallelism method parameter, so 
- tries to override a base method that does not exist,and
- fails to implement the Init method of the base class correctly.
Tested on .net7.0 Windows 11 with Visual Studio 2022 (+Resharper)

**Comment by satohikaru** [comment]
Issue Still Exists with MessagePack 3.1.4
I'm experiencing the exact same error with the following version combination:

Environment:

MasterMemory: 3.0.4
MessagePack: 3.1.4
.NET version: 8.0
Platform: .NET/Unity
Error Message:

MasterMemory.SourceGenerator\MasterMemory.SourceGenerator.MasterMemoryGenerator\MasterMemory.MemoryDatabase.g.cs(73,33): error CS0115: 'MemoryDatabase.Init(Dictionary<string, (int offset, int count)>, ReadOnlyMemory, MessagePackSerializerOptions, int)': no suitable method found to override

Root Cause Analysis: According to the MasterMemory 3.0.4 release notes (https://github.com/Cysharp/MasterMemory/releases/tag/v.3.0.4), it updated MessagePack dependency to 3.1.3. However, I'm experiencing this issue even with MessagePack 3.1.3, suggesting there may be an incompatibility between MasterMemory 3.0.4 and MessagePack 3.1.x series.

Attempted Workarounds: I tried downgrading MessagePack to 3.1.3, but the issue persists:

dotnet remove package MessagePack dotnet add package MessagePack --version 3.1.3

Request: Could you please investigate the compatibility between MasterMemory 3.0.4 and MessagePack 3.1.x? It appears the generated code is looking for a method signature that doesn't exist in the MessagePack 3.1.x series. A fix or clarification on the compatible MessagePack version would be greatly appreciated.

This issue is blocking users from using MasterMemory 3.0.4 with recent MessagePack versions. Thank you for your consideration!
